### ISSUE TITLE
Redesign Menu Field

### ISSUE THREAD

**Issue by GlacialBlaze** [LucasPilla/Sorting-Algorithms-Visualizer#127]
@mugulmd

Now let us add a vertical menu on the left and move the widgets to it, as such:

![image](https://user-images.githubusercontent.com/67182916/131811670-bbbd9eda-b5f6-4173-9de3-4fa638cf099e.png)

**Comment by mugulmd** [comment]
Ok, I have 2 questions though : 
- are both the play and stop buttons constantly displayed, or do they switch from one to the other when clicked (like in the current display) ?
- do you want to use the gui package I wrote or keep using the widget classes defined in dispay.py ?

**Comment by GlacialBlaze** [comment]
1) The two buttons should actually be the original one so, that particularly you can ignore the image.
2) Is it possible to keep the widget classes before we introduce changes to them? So that we can see any change systematically.

**Comment by LucasPilla** [comment]
@GlacialBlaze Feel free to accept and merge any pull request. Just make sure to not overload the program with useless features and keep the interface as clean as possible. Thank you for helping :)

**Comment by GlacialBlaze** [comment]
@LucasPilla

Will do!

Don't worry - keeping the interface as clean and minimal as possible, with only the most important things is my top priority. That's why previously I ensured the major pull request contains only the most useful and required-only stuff.

**Comment by mugulmd** [comment]
>     1. The two buttons should actually be the original one so, that particularly you can ignore the image.
> 
>     2. Is it possible to keep the widget classes before we introduce changes to them? So that we can see any change systematically.

@GlacialBlaze ok it shouldn't be too hard I'll keep you updated :)

**Comment by mugulmd** [comment]
Actually it causes a bunch of problems I did not anticipate, the 2 major ones being : 
- since the label of every widget is contained in the same object as the widget itself, every draw() method has to be rewritten to write the label on the left of the widget instead of on top of it 
- when clicking on the algorithms button, most of the algorithm names are out of the screen and there's no way to scroll in order to reach them.

@GlacialBlaze I don't know what you think about all this, but from my perspective it would be cleaner and easier to work with a more solid GUI structure (even though I hear you when you say it's a pretty big step to take).
What's your opinion on this ?

**Comment by GlacialBlaze** [comment]
@mugulmd

I see. I too am surprised by these.

- As a quick fix for problem 1, I've refactored the code for one of the classes to become a child of the main class which we create 'labelled' boxes. Please see if the new code helps. [#131]

- For problem 2, is it possible that you attempt to make another file of the original code (where everything is still a menu at the bottom) and try to make changes to the `Algorithm/Sort` box only? Doing so, it'll be easier to focus the changes on only that one box. Then, we'll be able to see if a vertical slider menu is possible after clicking the box.

**Comment by mugulmd** [comment]
Ok I'll try that and I'll keep you updated in the following days :)

**Comment by mugulmd** [comment]
Sorry for the delay ^^
I just did the pull request, it seems to work fine : #132
