### ISSUE TITLE
Bogo sort not working properly

### ISSUE THREAD

**Issue by shivamAmrutia** [LucasPilla/Sorting-Algorithms-Visualizer#163]
i recently cloned this repo to understand it better and was going through the app when i noticed that the bogo sort gif was not working properly

### **while sorting** 
it was stuck at the first parts of the given values

![bogo-whiles](https://user-images.githubusercontent.com/85829459/216802904-7e54a49f-f1e0-4873-885b-d439babd5cef.PNG)

### **after sorting**
it gave unsorted results

![bogo-sorted](https://user-images.githubusercontent.com/85829459/216802917-1fce14ee-49f1-412e-8e2e-2af03c0b30b7.PNG)

i tested this for a few times to make sure

i think it is because of the infinite upper limit here 

_i would like to work on this issue, kindly waiting for feedback from contributors_

**Comment by LucasPilla** [comment]
@shivamAmrutia Actually the bogosort isn't expected to work 🤣. It's just a random algorithm.

https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/blob/7ee00c35dcbabb1fd6f20e1bdb04a8bae8d50e9a/src/algorithms/bogoSort.py#L4-L12

Btw, i should remove it. You can do it if you want.

**Comment by shivamAmrutia** [comment]
Alright i think i will just add some text that is triggered when time limit is exceeded 😅 , looks better ig

**Comment by LucasPilla** [comment]
@shivamAmrutia You could just delete it, it's there just for the meme 🤣

**Comment by lucasrafaldini** [comment]
Hey, guys. Do you think deleting is the best alternative? I'm not sure about that because either its a meme or not, it has a name and a method and both are common conventions, so I think it's nice for beginners to (at least) know what this sh*t is at all lol

I mean... This repo isn't just about visualising the algorithms but also about reading its docstrings and understanding how its implemented and for what ends it is being used for (or not). So, deleting it would make it less complete, don't you think?
